[2021-08-16 15:06:05,334] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: spotify-etl.check_db_connection 2021-08-16T15:06:01.724909+00:00 [queued]>
[2021-08-16 15:06:05,362] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: spotify-etl.check_db_connection 2021-08-16T15:06:01.724909+00:00 [queued]>
[2021-08-16 15:06:05,362] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-16 15:06:05,363] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-16 15:06:05,363] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-16 15:06:05,384] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): check_db_connection> on 2021-08-16T15:06:01.724909+00:00
[2021-08-16 15:06:05,389] {standard_task_runner.py:52} INFO - Started process 810 to run task
[2021-08-16 15:06:05,393] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spotify-etl', 'check_db_connection', '2021-08-16T15:06:01.724909+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/spotify-etl.py', '--cfg-path', '/tmp/tmp6_6e2awn', '--error-file', '/tmp/tmp1kilb6y8']
[2021-08-16 15:06:05,394] {standard_task_runner.py:77} INFO - Job 17: Subtask check_db_connection
[2021-08-16 15:06:05,443] {logging_mixin.py:104} INFO - Running <TaskInstance: spotify-etl.check_db_connection 2021-08-16T15:06:01.724909+00:00 [running]> on host 4095d62d00ed
[2021-08-16 15:06:05,497] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spotify-etl
AIRFLOW_CTX_TASK_ID=check_db_connection
AIRFLOW_CTX_EXECUTION_DATE=2021-08-16T15:06:01.724909+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-16T15:06:01.724909+00:00
[2021-08-16 15:06:05,499] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/spotify-etl.py", line 75, in check_postgresql_connection
    params = config()
  File "/opt/airflow/dags/modules/config.py", line 17, in config
    raise Exception('Section {0} not found in the {1} file'.format(section, filename))
Exception: Section postgresql not found in the database.ini file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/spotify-etl.py", line 85, in check_postgresql_connection
    raise Exception(("Error connecting to database: {error}".format(error=error)))
Exception: Error connecting to database: Section postgresql not found in the database.ini file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify-etl.py", line 87, in check_postgresql_connection
    if conn is not None:
UnboundLocalError: local variable 'conn' referenced before assignment
[2021-08-16 15:06:05,508] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=spotify-etl, task_id=check_db_connection, execution_date=20210816T150601, start_date=20210816T150605, end_date=20210816T150605
[2021-08-16 15:06:05,565] {local_task_job.py:149} INFO - Task exited with return code 1
